version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 8uLGJBy9waWXDFZGdqXdQM5T6BxoWgr3HN001a+ThvnhRUL0XFTQ7pjOoKsWZSzt
  on:
    branch: master