version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  strong_name_secret:
    secure: aENMghJNRZX34pkCa7iU53Sd438em4NMPOsFF17rnW0=
install:
- ps: >-
    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt .\Articulate.snk.enc -secret $($env:strong_name_secret)
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
artifacts:
- path: '**\System.Doubles.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 8uLGJBy9waWXDFZGdqXdQM5T6BxoWgr3HN001a+ThvnhRUL0XFTQ7pjOoKsWZSzt
  on:
    branch: master