//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Articulate Framework")]
[assembly: AssemblyCompany("Articulate Global, Inc.")]
[assembly: AssemblyVersion("6.0.0.0")]
[assembly: AssemblyInformationalVersion("6.0.0.0 LOCAL")]
[assembly: AssemblyCopyright("© 2001-2016 Articulate Global, Inc. All rights reserved.")]
[assembly: AssemblyTrademark("Articulate and Articulate 360 are trademarks or registered trademarks of Articulate Global, Inc. in the United States and other countries.")]